/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/OQiQMXVuRpK
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    (<div className="flex items-center justify-center min-h-screen bg-gray-900">
      <Card
        className="w-full max-w-md p-6 space-y-6 bg-gray-800 border border-gray-700">
        <div className="flex items-center space-x-4">
          <div
            className="w-24 h-24 bg-gray-700 flex items-center justify-center text-white">product image</div>
          <div className="space-y-2">
            <Label htmlFor="product-name" className="text-white">
              product name
            </Label>
            <Input
              id="product-name"
              placeholder="product name"
              className="bg-gray-700 text-white" />
          </div>
        </div>
        <div className="space-y-2">
          <Label htmlFor="product-description" className="text-white">
            product description
          </Label>
          <Input
            id="product-description"
            placeholder="product description"
            className="bg-gray-700 text-white" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="price" className="text-white">
            price
          </Label>
          <Input id="price" placeholder="price" className="bg-gray-700 text-white" />
        </div>
        <p className="text-gray-400">here, all fields are editable</p>
        <Button className="w-full bg-gray-700 text-white border border-gray-600">submit changes for approval</Button>
      </Card>
    </div>)
  );
}
